--- 
deployment: 
  tasks:     
    - export NODEBIN=/home/systema1/nodevenv/dev/20/bin 
    - export REPOPATH=/home/systema1/repositories/webstore 
    # Node.js application root (your running app) 
    - export APPROOT=/home/systema1/dev 
    # Install Dependencies in the repo folder 
    - $NODEBIN/npm install --prefix $REPOPATH 
    # Build React App 
    - $NODEBIN/npm run build --prefix $REPOPATH 
    # Deploy build output 
    - /bin/rsync -av --delete $REPOPATH/build/ $DEPLOYPATH/ 
    # Restart Node.js app 
    - /usr/local/bin/ea-nodejs-cli --app /home/systema1/dev restart