name: Build

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Increment build number
        run: |
          BUILD=$(cat build_number.txt)
          BUILD=$((BUILD + 1))
          echo $BUILD > build_number.txt
          echo "REACT_APP_BUILD_NUMBER=$BUILD" >> $GITHUB_ENV

      - name: Commit updated build number
        run: |
          sed -i "s/{{BUILD_NUMBER}}/$BUILD/g" src/App.js
          git config user.name "CI"
          git config user.email "general@systematicdefence.tech"
          git add build_number.txt
          git commit -m "Increment build number to $BUILD" || echo "No changes"
          git push || true

      - name: Build React app
        run: npm run build
